# Generated by Django 3.1.7 on 2021-03-05 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210305_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='note',
            field=models.CharField(default=datetime.datetime(2021, 3, 5, 12, 21, 54, 939006, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(default=datetime.datetime(2021, 3, 5, 12, 21, 58, 776076, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
