# Generated by Django 3.1.7 on 2021-03-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210305_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='note',
            field=models.CharField(blank=True, default=1, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, default=1, max_length=200, null=True),
        ),
    ]
